server:
  port: 8080

datasource:
  driverName: mysql
  host: 192.168.31.155
  port: 3306
  database: ustoj
  username: root
  password: 123456
  charset: utf8

logger:
  writeFile: true
  level: info

kubernetes:
  masterUrl: https://192.168.31.80:6443
  masterConfig: /tmp/kubernetes_admin_config/admin.conf